### ISSUE TITLE
Chapters 17 and 18 are not working

### ISSUE THREAD

**Issue by nimelord** [lwjglgamedev/lwjglbook#12]
Other chapters are - ok.

Use command: mvn clean package exec:java

try on two gpu platforms:

1. Renderer: NVIDIA GeForce GTX 960M/PCIe/SSE2 Version: 4.3.0 NVIDIA 525.147.05
2. Renderer: Mesa Intel(R) HD Graphics 530 (SKL GT2) Version: 4.6 (Core Profile) Mesa 22.3.6

OS: debian 11

output:
java.lang.RuntimeException: Could not find uniform [shadowMap_0] in shader program [1]
    at org.lwjglb.engine.graph.UniformsMap.createUniform (UniformsMap.java:24)
    at org.lwjglb.engine.graph.SceneRender.createUniforms (SceneRender.java:77)
    at org.lwjglb.engine.graph.SceneRender.<init> (SceneRender.java:24)
    at org.lwjglb.engine.graph.Render.<init> (Render.java:25)
    at org.lwjglb.engine.Engine.<init> (Engine.java:25)
    at org.lwjglb.game.Main.main (Main.java:28)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:840)

**Comment by nimelord** [comment]
Also the question:
Why do you not use GL_TEXTURE_2D_ARRAY instead of three different GL_TEXTURE_2D for cascade shadow mapping ?

**Comment by lwjglgamedev** [comment]
Hi, I will have a look during the weekend. Yo need diferent textures per cascade shadow, therfore you need an array of textures. Is this waht you wer asking for?

**Comment by nimelord** [comment]
No, the case is - You are using

uniform sampler2D shadowMap_0;
uniform sampler2D shadowMap_1;
uniform sampler2D shadowMap_2;

Why not

uniform sampler2DArrayShadow dlShadowMap;
or
uniform sampler2DArray dlShadowMap;
?

**Comment by lwjglgamedev** [comment]
Ok, understood now. It could be used also the approahc you mention, keep in mind however that an array of samplers allows you to use tetxures with different sizes (which is not  possible with a sampler2Darray). In the example, since all the textures have the same dimension you could use them also.

In any case I will provide a fix using an array of samplers.

**Comment by nimelord** [comment]
What the target of your activity?
Do You produce the education resources, that is the target?
You are very well with it, I sure.)

**Comment by lwjglgamedev** [comment]
The answer is not so easy. I initially started this as a self documenting project for my learning process about OpenGL (when I started this I hadn't used OpenGL at all). After that It thought it could be useful to somebody else. So no specific target in mind.

Going back to the issue. The good news is that I've been able to reproduce the issue on Linux (PopOS in my case). The funny thing is that it is working perfectly on Windows. In any case, the fix is easy, just use an array  of samplers or, as you suggest, a sampler2DArray. I cannot recall why I did not use that approach. In fact, the samples for my Vulkan book use a sampler2DArray. In order to keep thinks simple I may go with the array of samplers approach, but mentioning also the possibility of using a sampler2DArray.

I will upload the fix during the weekend.

Thanks for reporting!

**Comment by lwjglgamedev** [comment]
I've already uploaded a fix. If you think there is still something missing, please reopen.

**Comment by nimelord** [comment]
Good, there was version of slgl.
There is interesting thing, that it was working on win)

It is can be running now, but something wrong with shadows.

![image](https://github.com/lwjglgamedev/lwjglbook/assets/21811792/f4dfff42-da88-4027-a794-7d3e5a32816b)

**Comment by lwjglgamedev** [comment]
Ok, good to know. I will try to find out what is happening. I cannot promise when I will be able to check this. I will reopen the issue to try not to forget it.
