### ISSUE TITLE
chapter-07/src/main/java/org/lwjglb/engine/graph/SceneRender.java has invalid code

### ISSUE THREAD

**Issue by Domochevsky** [lwjglgamedev/lwjglbook#5]
**Describe the bug**
**Line 38** in the file **SceneRender.java** in chapter 7 says
`uniformsMap.setUniform("txtSampler", 0);`

However, `0` is not a valid input for that function. It expects `Matrix4f` there, but got an `int`.

**To Reproduce**
Just paste the relevant lines into your IDE and watch it complain, I guess.

**Expected behavior**
Either for the function to accept 0, or to know what to put there instead. It seems to be about texture unit slots on the graphics card.

**Comment by lwjglgamedev** [comment]
Hi,

Many thanks for reporting. The source code is correct. If you clone it from the repo it will compile. The issue was with the text of the chapter 7, which did not explain the modifications required in the `UniformsMap` class. I've just uploaded a fix for that. If you think there is still a bug in the source code, please reopen.
