### ISSUE TITLE
Arrows, delete and backspace not binded

### ISSUE THREAD

**Issue by FrequentlyMissedDeadlines** [lwjglgamedev/lwjglbook#8]
**Describe the bug**
If you use the demo GUI and write text in an InputText, the standard characters will work but it's not possible to use the arrows to navigate in the string or to delete characters with DEL or BACKSPACE.

**To Reproduce**
1. open any chapter (I did it with chapter 10 since it's where we introduce GUI)
2. in the Dear ImGui Demo window go to Widgets > Text Input > Filtered Text Input
3. type text
4. try to delete it

**Expected behavior**
All keys should be mapped.

**Screenshots**
not needed

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
I tried to figure out how to solve it but I'm new to these topics and would appreciate your help.
Actually I like your book it's really well detailed and I like the way you structure the code.

**Comment by lwjglgamedev** [comment]
Thanks for reporting. I will have a look al it as soon as I can (not sooner than a week)

**Comment by lwjglgamedev** [comment]
Already uploaded a fix. The issue was that I was not correctlt seeting the key map which translates GLFW key codes to the ones used by ImGui to handle special key events which are required for some widgets (such as text widgets). It should work with this fix. If there is still some other issue, please re-open.
